HomeWallet/Controllers/DailySummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWallet.Data;
using HomeWallet.Logic.DailySummary;
using HomeWallet.Models;
using HomeWallet.Models.DailySummaryViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Highsoft.Web.Mvc.Charts;
namespace HomeWallet.Controllers
{
    public class DailySummaryController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public DailySummaryController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        // GET: DailySummary
        public ActionResult Index(DateTime date)
        {
            var percentage = DailySummary.GetPercentage(_context,date,_userManager.GetUserId(HttpContext.User));
            List<PieSeriesData> pieData = new List<PieSeriesData>();
            pieData.Add(new PieSeriesData 
            { 
                Name = date.ToString("dd-MM-yyyy"), 
                Y = percentage, 
                Sliced = true, 
                Selected = true, 
                Color="white"
            });
            pieData.Add(new PieSeriesData 
            { 
                Name = "Plan", 
                Y = 100-percentage, 
                Sliced = true, 
                Selected = true, 
                Color="#222"
            });

            ViewData["pieData"] = pieData;

            var model = new DailySummaryViewModel()
            {
                TotalCost = DailySummary.GetAllMoney(_context,date,_userManager.GetUserId(HttpContext.User)),
                Date = date.ToString("dd-MM-yyyy"),
                Percent = percentage,
                Currency = "zł"
            };
            return View(model);
        }
    }
}

HomeWallet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWallet.Data;
using HomeWallet.Logic.Home;
using HomeWallet.Models;
using HomeWallet.Models.ReceiptViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HomeWallet.Controllers
{
    public class HomeController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if(User.Identity.IsAuthenticated)
            {
                return View();
            }
            return View("MainPage");
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult GetReceipts(string lastDate)
        {
            var dates = LoadHomeReceipts.GetDates(lastDate,_userManager.GetUserId(HttpContext.User),_context);
            if (dates!=null)
            {
              var model = LoadHomeReceipts.GetHomeReceiptViewModels(dates.ToList(),_userManager.GetUserId(HttpContext.User), _context);
              return PartialView(model);
            }
            return null;
        }
    }
}

HomeWallet/Controllers/ReceiptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HomeWallet.Data;
using HomeWallet.Logic.Products;
using HomeWallet.Models;
using HomeWallet.Models.ProductViewModels;
using HomeWallet.Models.ReceiptViewModels;
using Microsoft.AspNetCore.Identity;

namespace HomeWallet.Controllers
{
    public class ReceiptsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ReceiptsController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Receipts
        public async Task<IActionResult> Index()
        {
            return RedirectToAction("Index","Home");
        }

        // GET: Receipts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .Include(r => r.Shop)
                .Include(r => r.User)
                .Include(r=>r.ReceiptProducts).ThenInclude(p=>p.Product)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (receipt == null)
            {
                return NotFound();
            }
            double total = 0;

            var products = new List<DetailsProductViewModel>();
            foreach (var receiptproduct in receipt.ReceiptProducts)
            {
                products.Add(new DetailsProductViewModel()
                {
                    Amount = receiptproduct.Amount,
                    Price = receiptproduct.Price,
                    Product = receiptproduct.Product.Name,
                    Total = receiptproduct.Amount* receiptproduct.Price
                });
                total += receiptproduct.Amount * receiptproduct.Price;
            }
            var model = new ReceiptDetailsViewModel()
            {
                ID = receipt.ID,
                PurchaseDate = receipt.PurchaseDate,
                Shop = receipt.Shop.Name,
                Total = total,
                Products = products
            };


            return View(model);
        }


        public IActionResult CreateCyclical(DateTime date)
        {
            if (date == default(DateTime))
            {
                date = DateTime.Today;
            }
            var model = new CreateCyclicalReceiptViewModel()
            {
                StartDate = date.Date,
                EndDate = date.Date.AddDays(30)
            };
            var userid = _userManager.GetUserId(HttpContext.User);
            ViewData["ShopID"] = new SelectList(_context.Shops.Where(s=>s.UserID==userid), "ID", "Name");
            return View(model);
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCyclical(CreateCyclicalReceiptViewModel model)
        {
            if (ModelState.IsValid)
            {
                var start = model.StartDate;
                while (start<=model.EndDate)
                {
                    var receipt = CreateProduct.CreateReceipt(model.ShopID, _userManager.GetUserId(HttpContext.User), start, _context);
                    CreateProduct.CreateReceiptProducts(model.Products, receipt, _context);
                    start = start.AddMonths(model.Cycle);
                }
                return RedirectToAction("Index");
            }
            var userid = _userManager.GetUserId(HttpContext.User);
            ViewData["ShopID"] = new SelectList(_context.Shops.Where(s=>s.UserID==userid), "ID", "Name", model.ShopID);
            return View();
        }



        // GET: Receipts/Create
        public IActionResult Create(DateTime date)
        {
            if (date == default(DateTime))
            {
                date = DateTime.Today;
            }
            var model = new CreateReceiptViewModel()
            {
                Date = date.Date
            };
            var userid = _userManager.GetUserId(HttpContext.User);
            ViewData["ShopID"] = new SelectList(_context.Shops.Where(s=>s.UserID==userid), "ID", "Name");
            return View(model);
        }

        // POST: Receipts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateReceiptViewModel model)
        {
          if (ModelState.IsValid)
          {
            var receipt = CreateProduct.CreateReceipt(model.ShopID, _userManager.GetUserId(HttpContext.User), model.Date, _context);
            CreateProduct.CreateReceiptProducts(model.Products, receipt, _context);
            return RedirectToAction("Index");
          }
          var userid = _userManager.GetUserId(HttpContext.User);
          ViewData["ShopID"] = new SelectList(_context.Shops.Where(s => s.UserID == userid), "ID", "Name", model.ShopID);
          return View();
        }


        public PartialViewResult AddProduct()
        {
            var userid = _userManager.GetUserId(HttpContext.User);
            ViewData["Products"] = new SelectList(_context.Products.Where(p=>p.UserID ==userid),"ID","Name");
            ViewData["Categories"] = new SelectList(_context.Categories.Where(p=>p.UserID ==userid),"ID","Name");
            return PartialView("CreateProduct");
        }
        [HttpPost]
        public ViewResult AddProduct(CreateProductViewModel model)
        {
            var addModel = CreateProduct.CreateModel(model, _userManager.GetUserId(HttpContext.User), _context);
            return View(addModel);
        }
        [HttpPost]
        public ViewResult AddCyclicalProduct(CreateProductViewModel model)
        {
            var addModel = CreateProduct.CreateModel(model, _userManager.GetUserId(HttpContext.User), _context);
            return View(addModel);
        }

        public ViewResult CreateShop()
        {
            return View();
        }

        [HttpPost]
        public string[] AddShop(Shop model)
        {
            var shop = new Shop()
            {
                Name = model.Name,
                UserID = _userManager.GetUserId(HttpContext.User)
            };
            _context.Shops.Add(shop);
            _context.SaveChanges();
            var result = new string[2];
            result[0] = shop.ID.ToString();
            result[1] = shop.Name;
            return result;
        }

        // GET: Receipts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts.SingleOrDefaultAsync(m => m.ID == id);
            if (receipt == null)
            {
                return NotFound();
            }
            ViewData["ShopID"] = new SelectList(_context.Shops, "ID", "Name", receipt.ShopID);
            return View(receipt);
        }

        // POST: Receipts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,PurchaseDate,ShopID,UserID")] Receipt receipt)
        {
            if (id != receipt.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receipt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceiptExists(receipt.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["ShopID"] = new SelectList(_context.Shops, "ID", "Name", receipt.ShopID);
            return View(receipt);
        }

        // GET: Receipts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receipt = await _context.Receipts
                .Include(r => r.Shop)
                .Include(r => r.User)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (receipt == null)
            {
                return NotFound();
            }

            return View(receipt);
        }

        // POST: Receipts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var receipt = await _context.Receipts.SingleOrDefaultAsync(m => m.ID == id);
            _context.Receipts.Remove(receipt);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ReceiptExists(int id)
        {
            return _context.Receipts.Any(e => e.ID == id);
        }
    }
}

HomeWallet/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

HomeWallet/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HomeWallet/Views/Home/GetReceipts.cshtml
@model IEnumerable<HomeWallet.Models.ReceiptViewModels.HomeReceiptViewModel>

@foreach (var item in Model)
{
    <div class="container">
        <div class="row dayheader">
            <div class="col-xs-6 col-md-8 datetextfield">
                <label class="datefield">@Html.DisplayFor(modelitem =>item.Date)</label>
            </div>
            <div class="col-xs-6 col-md-4 summarybutton">
                <a class="btn btn-default" asp-action="Index" asp-controller="DailySummary" asp-route-date="@item.Date">Summary</a>
            </div>
        </div>
        <hr />
        @foreach (var receipt in item.Receipts)
        {
            <a asp-action="Details" asp-controller="Receipts" asp-route-id="@receipt.ID">
                <div class="col-md-3 col-xs-6 receiptsummary">
                    <div class="shoptextfield">
                        <h1>@Html.DisplayFor(modelitem => receipt.Shop)</h1>
                    </div>
                    <div class="pricetextfield">
                        <h3>@Html.DisplayFor(modelitem => receipt.Value)</h3>
                    </div>
                </div>
            </a>
        }
        <a href="@Url.Action("Create","Receipts", new {date=item.Date})">
          <div class="col-md-3 col-xs-6 receiptsummary">
            <div class="shoptextfield">
              <h1>Add</h1>
            </div>
            <div class="pricetextfield">
              <h3>new</h3>
            </div>
          </div>
        </a>
    </div>
}

HomeWallet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="loading">Loading...</div>
<div class="morereceipts"></div>

<div class="newuser">New user</div>

<div class="noreceipts">No more receipts.</div>
<div class="col-md-12 morebuttondiv">
    <button id="addreceiptbutton" class="btn btn-default showmorebutton">Show More</button>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
  $(document).one('ready', function () {
        $('.noreceipts').hide();
        $('.newuser').hide();
        getReceipts(0);
    });

    $('#addreceiptbutton').click(function() {
        var lastId;
        if ($('.datefield').last().text() != null) {
            lastId = $('.datefield').last().text();
        } else {
            lastId = 0;
        }
        getReceipts(lastId);
    });

    function getReceipts(last) {
      jQuery.get('/Home/GetReceipts',
        {
          lastDate: last
        })
        .done(function (html) {
          $('.morereceipts').append(html);
          $('.loading').remove();
        })
        .fail(function () {
            if($('.morereceipts').is(':empty'))
            {
                $('.newuser').show();
            }
            else
            {
                $('.noreceipts').show();
            }
            $('.morebuttondiv').hide();
            $('.loading').hide();
          });
    }
</script>

HomeWallet/Views/Home/MainPage.cshtml
@{
    Layout = "_MainPageLayout";
}
<div class="mainphoto">
    <div class="mainheader">
        <h1 class="maintitle">Home Wallet</h1>
        <h2 class="maintext">Your home financial app</h2>
    </div>
    <div>
        <div class="col-md-6 col-sm-12 registerbutton">
            <a class="btn btn-info " asp-controller="Account" asp-action="Register">Register</a>
        </div>
        <div class="col-md-6 col-sm-12 loginbutton">
            <a class="btn btn-success" asp-controller="Account" asp-action="Login">Log in</a>
        </div>
    </div>
</div>